### ISSUE TITLE
Hide "Unloved" link in nav bar if there are no unloved photos

### ISSUE THREAD

**Issue by kingdomlevel** [kingdomlevel/coconut_gallery#20]
This should be a simple fix, I think line 24 in `app/views/layouts/application.html.erb`

**Comment by kingdomlevel** [comment]
Have defeated the major blocker in this!

It was a `meta` tag in the html head - so media queries should still work as expected.

Created branch + tidied file structure in prep for this work

**Comment by 87johnboyle** [comment]
Submitted a pull request for this.
